<?php
namespace LWS\WOOCURRENCY;

// don't call the file directly
if( !defined( 'ABSPATH' ) ) exit();

use \LWS\Adminpanel as AP;

/** Keep a hard written array with country as key and currency as value. */
class CountryCurrencyList
{
	/** Search a currency from a country.
	 * @return string|false */
	public static function find($idCountry)
	{
		$countryList = self::get();
		return (isset($countryList[$idCountry])) ? $countryList[$idCountry] : false;
	}

	/** Search a country array from a currency.
	 * @return array|false */
	public static function rFind($currency)
	{
		$currencyList = self::reverse();
		return (isset($currencyList[$currency])) ? $currencyList[$currency] : false;
	}

	/** Build an array with currency as key and country array as value. */
	public static function reverse()
	{
		static $currencyCountryList = false;
		if( $currencyCountryList === false )
		{
			$currencyCountryList = array();
			foreach( self::get() as $k=>$v )
				$currencyCountryList[$v][] = $k;
		}
		return $currencyCountryList;
	}

	/** @return JSON */
	public static function reverseToString()
	{
		$rev = self::reverse();
		ksort($rev, SORT_STRING);
		return json_encode($rev);
	}

	public static function get()
	{
		return array(
			"TW" => "USD",
			"AF" => "AFN",
			"AL" => "ALL",
			"DZ" => "DZD",
			"AS" => "USD",
			"AD" => "EUR",
			"AO" => "AOA",
			"AI" => "XCD",
			"AQ" => "USD",
			"AG" => "XCD",
			"AR" => "ARS",
			"AM" => "AMD",
			"AW" => "AWG",
			"AU" => "AUD",
			"AT" => "EUR",
			"AZ" => "AZN",
			"BS" => "BSD",
			"BH" => "BHD",
			"BD" => "BDT",
			"BB" => "BBD",
			"BY" => "BYN",
			"BE" => "EUR",
			"BZ" => "BZD",
			"BJ" => "XOF",
			"BM" => "BMD",
			"BT" => "USD",
			"BO" => "BOB",
			"BQ" => "USD",
			"BA" => "BAM",
			"BW" => "BWP",
			"BV" => "NOK",
			"BR" => "BRL",
			"IO" => "USD",
			"VG" => "USD",
			"BN" => "BND",
			"BG" => "BGN",
			"BF" => "XOF",
			"BI" => "BIF",
			"CV" => "CVE",
			"KH" => "KHR",
			"CM" => "XAF",
			"CA" => "CAD",
			"KY" => "KYD",
			"CF" => "XAF",
			"TD" => "XAF",
			"CL" => "CLP",
			"CN" => "CNY",
			"HK" => "HKD",
			"MO" => "MOP",
			"CX" => "AUD",
			"CC" => "AUD",
			"CO" => "COP",
			"KM" => "KMF",
			"CG" => "XAF",
			"CK" => "NZD",
			"CR" => "CRC",
			"HR" => "HRK",
			"CU" => "USD",
			"CW" => "ANG",
			"CY" => "EUR",
			"CZ" => "CZK",
			"CI" => "XOF",
			"KP" => "KPW",
			"CD" => "CDF",
			"DK" => "DKK",
			"DJ" => "DJF",
			"DM" => "XCD",
			"DO" => "DOP",
			"EC" => "USD",
			"EG" => "EGP",
			"SV" => "USD",
			"GQ" => "XAF",
			"ER" => "ERN",
			"EE" => "EUR",
			"ET" => "ETB",
			"FK" => "USD",
			"FO" => "DKK",
			"FJ" => "FJD",
			"FI" => "EUR",
			"FR" => "EUR",
			"GF" => "EUR",
			"PF" => "XPF",
			"TF" => "EUR",
			"GA" => "XAF",
			"GM" => "GMD",
			"GE" => "GEL",
			"DE" => "EUR",
			"GH" => "GHS",
			"GI" => "GIP",
			"GR" => "EUR",
			"GL" => "DKK",
			"GD" => "XCD",
			"GP" => "EUR",
			"GU" => "USD",
			"GT" => "GTQ",
			"GG" => "GBP",
			"GN" => "GNF",
			"GW" => "XOF",
			"GY" => "GYD",
			"HT" => "USD",
			"HM" => "AUD",
			"VA" => "EUR",
			"HN" => "HNL",
			"HU" => "HUF",
			"IS" => "ISK",
			"IN" => "INR",
			"ID" => "IDR",
			"IR" => "IRR",
			"IQ" => "IQD",
			"IE" => "EUR",
			"IM" => "GBP",
			"IL" => "ILS",
			"IT" => "EUR",
			"JM" => "JMD",
			"JP" => "JPY",
			"JE" => "GBP",
			"JO" => "JOD",
			"KZ" => "KZT",
			"KE" => "KES",
			"KI" => "AUD",
			"KW" => "KWD",
			"KG" => "KGS",
			"LA" => "LAK",
			"LV" => "EUR",
			"LB" => "LBP",
			"LS" => "USD",
			"LR" => "LRD",
			"LY" => "LYD",
			"LI" => "CHF",
			"LT" => "EUR",
			"LU" => "EUR",
			"MG" => "MGA",
			"MW" => "MWK",
			"MY" => "MYR",
			"MV" => "MVR",
			"ML" => "XOF",
			"MT" => "EUR",
			"MH" => "USD",
			"MQ" => "EUR",
			"MR" => "MRO",
			"MU" => "MUR",
			"YT" => "EUR",
			"MX" => "MXN",
			"FM" => "USD",
			"MC" => "EUR",
			"MN" => "MNT",
			"ME" => "EUR",
			"MS" => "XCD",
			"MA" => "MAD",
			"MZ" => "MZN",
			"MM" => "MMK",
			"NA" => "USD",
			"NR" => "AUD",
			"NP" => "NPR",
			"NL" => "EUR",
			"NC" => "XPF",
			"NZ" => "NZD",
			"NI" => "NIO",
			"NE" => "XOF",
			"NG" => "NGN",
			"NU" => "NZD",
			"NF" => "AUD",
			"MP" => "USD",
			"NO" => "NOK",
			"OM" => "OMR",
			"PK" => "PKR",
			"PW" => "USD",
			"PA" => "USD",
			"PG" => "PGK",
			"PY" => "PYG",
			"PE" => "PEN",
			"PH" => "PHP",
			"PN" => "NZD",
			"PL" => "PLN",
			"PT" => "EUR",
			"PR" => "USD",
			"QA" => "QAR",
			"KR" => "KRW",
			"MD" => "MDL",
			"RO" => "RON",
			"RU" => "RUB",
			"RW" => "RWF",
			"RE" => "EUR",
			"BL" => "EUR",
			"SH" => "SHP",
			"KN" => "XCD",
			"LC" => "XCD",
			"MF" => "EUR",
			"PM" => "EUR",
			"VC" => "XCD",
			"WS" => "WST",
			"SM" => "EUR",
			"ST" => "STD",
			"SA" => "SAR",
			"SN" => "XOF",
			"RS" => "RSD",
			"SC" => "SCR",
			"SL" => "SLL",
			"SG" => "SGD",
			"SX" => "ANG",
			"SK" => "EUR",
			"SI" => "EUR",
			"SB" => "SBD",
			"SO" => "SOS",
			"ZA" => "ZAR",
			"GS" => "USD",
			"SS" => "SSP",
			"ES" => "EUR",
			"LK" => "LKR",
			"PS" => "USD",
			"SD" => "SDG",
			"SR" => "SRD",
			"SJ" => "NOK",
			"SZ" => "SZL",
			"SE" => "SEK",
			"CH" => "CHF",
			"SY" => "SYP",
			"TJ" => "TJS",
			"TH" => "THB",
			"MK" => "MKD",
			"TL" => "USD",
			"TG" => "XOF",
			"TK" => "NZD",
			"TO" => "TOP",
			"TT" => "TTD",
			"TN" => "TND",
			"TR" => "TRY",
			"TM" => "TMT",
			"TC" => "USD",
			"TV" => "AUD",
			"UG" => "UGX",
			"UA" => "UAH",
			"AE" => "AED",
			"GB" => "GBP",
			"TZ" => "TZS",
			"UM" => "USD",
			"VI" => "USD",
			"US" => "USD",
			"UY" => "UYU",
			"UZ" => "UZS",
			"VU" => "VUV",
			"VE" => "VEF",
			"VN" => "VND",
			"WF" => "XPF",
			"EH" => "MAD",
			"YE" => "YER",
			"ZM" => "ZMW",
			"ZW" => "ZWL",
			"AX" => "EUR"
		);
	}
}
